### ISSUE TITLE
IFunBox crash

### ISSUE THREAD

**Issue by lougehrig10** [kpwn/yalu102#317]
IOS 10.2 IPhone 5s

When using IFunBox to browse the iphones files, IFunBox crashes as well as ios freezing

**Comment by DarknesGaming** [comment]
Do you have Apple File Conduit 2 installed? If not, that might be the problem.
That does open a security hole, so you should use a File Manager that you can find on Cydia. Filza and iFile are 2 file managers.
Also, this is not a code-related issue, but #64 is a bad reference because this has nothing to do with device support. xD

**Comment by bobbysn0w** [comment]
#162 
BUT Filza has some server thingy that works with your browser and iFunBox check it out in it's settings

**Comment by lougehrig10** [comment]
Ok, I'll close the thread, I just re-installed IFunBox and it stopped crashing, but didn't view files (With Apple File Conduit 2)
