### ISSUE TITLE
Can't SSH into device

### ISSUE THREAD

**Issue by simsdj** [kpwn/yalu102#393]
This is not a support forum or generic mailing list.

This form is exclusively for reporting issues caused directly by the inner workings of yalu.

Direct your jailbreaking questions to one of these fine communities:

* https://reddit.com/r/jailbreak
* http://www.jailbreakqa.com/

Issues, which are not related to yalu's code, may be closed without comment. Do NOT post about: Cydia, tweak, respring/bootloop or app issues UNLESS you have evidence that they are caused by an error in the jailbreaking software itself.

(Delete this bit after reading, and replace it by "I read the issue posting guidelines.")

**Comment by simsdj** [comment]
I fucked up some of my stuff so I was trying to use prometheus to restore but one of the steps requires I SSH into my phone and when I try to do so, nothing happens

**Comment by XAVERRenogadeAngle** [comment]
Close this......   The fact that people continue to post stupid shit makes me want to give up on humanity.

You have to update to 10.2.1 then downgrade. SHSH will still be active after updating that's how Yalu works. If you messed stuff up with tweaks this is the only way. Use the 10.2.1 shsh blobs when you go back to 10.2 the Yalu exploit is still dormant on you're phone which allows for the 10.2.1 blobs to sign the restore. I'd wait for the gama release before jailbreaking. Make sure to do this as soon a possible because Apple is going to close this bug soon. It's pacthable form their side. 
Good luck.
