### ISSUE TITLE
Removed cydia

### ISSUE THREAD

**Issue by Fremder** [kpwn/yalu102#408]
Hey Guys,
I know i did a mistake and removed Cydia could anyone explain me how i get it back got 10.1.1 on an 5S (got a mac if needed)

**Comment by ghCadia** [comment]
Not a code issue please close.
But I will help install this deb of cydia and your all good.
[apt.saurik.com/debs/cydia_1.1.28_iphoneos-arm.deb](url)

Please ask on the Jailbreak Reddit for help and not here this is only for code issues and not your own mistakes.

**Comment by NickGP** [comment]
#162 #64

**Comment by NickGP** [comment]
Btw, google it or look on reddit, tons of people have tutorials

**Comment by modz2014** [comment]
install Mobile terminal then do 

apt-get install cydia 
apt-get update 
apt-get upgrade
apt-get auto clean

**Comment by kpwn** [comment]
SSH is included, use it

**Comment by cydiasnotthere** [comment]
First reset your iPhone so you have the option to press go on Yalu but don't do it yet, now go to your computer and download ifunbox open it then go to quicktoolbox, plug in your iPhone and open USB tunnel. A code should appear if you did it right. Now go to Yalu and click go until you get Cydia. Hope it works for you because it worked for me.
