### ISSUE TITLE
iPad air2 random resprings 

### ISSUE THREAD

**Issue by haze4** [kpwn/yalu102#410]
This is not a support forum or generic mailing list.

This form is exclusively for reporting issues caused directly by the inner workings of yalu.

Direct your jailbreaking questions to one of these fine communities:

* https://reddit.com/r/jailbreak
* http://www.jailbreakqa.com/

Issues, which are not related to yalu's code, may be closed without comment. Do NOT post about: Cydia, tweak, respring/bootloop or app issues UNLESS you have evidence that they are caused by an error in the jailbreaking software itself.

(Delete this bit after reading, and replace it by "I read the issue posting guidelines.")

**Comment by haze4** [comment]
Ok I'm jailbroken on ipadair2 on 10.2 I've nothing installed at all only updated today to the new version of Cydia and it's still respringing randomly , it done it before I had the updated version of Cydia installed and it's still doing it now after I've installed the new version . And when I press go to reinable the jailbreak it will take up to 20+ attempts ,was told on here that it was respringing because I hadn't the latest version of Cydia installed, well it's still doing it . Hopefully qwertyuiop plans an update to fix this , any info regarding this will be greatly appreciated, 😁

**Comment by ghost** [comment]
The thread is for code related issues only. kpwn knows there are issues with the iPad 5,X series (iPad Air 2 etc) but it is a lot of pain for him to resolve these issues easily. 
I have documented somethings that may help here:
https://www.reddit.com/r/jailbreak/comments/5sgbyp/tutorial_readding_cydia_in_case_of_loss_ios_102/
Alternatively the Jailbreak reddit page has some potential issue solvers that may help you.

However due to the issue being off topic, it is recommended you close the issue as it has nothing to do with the code that kpwn doesn't already know.

**Comment by haze4** [comment]
Ok but do you think he will fix resprings

**Comment by ghost** [comment]
@haze4 
Random resprings happen to the devices due to the jailbreak's instability. I would imagine eventually the issue will be fixed, but there is no specified timeframe to which the issue might be fixed. Keep looking around and hopefully something on the reddit forum may help you. Happy Jailbreaking.
