### ISSUE TITLE
cydia not working

### ISSUE THREAD

**Issue by ajdrsx** [kpwn/yalu102#76]
cydia opens, but does not work. iphone 6s plus

**Comment by Asddsaasdihmk** [comment]
try using the app that installed it again

**Comment by olirehacek** [comment]
This is not a place to solve this kind of issues. Keep it code related !

**Comment by miayotlan** [comment]
Please someone  add this to the read me file so they can just go straight here   https://www.reddit.com/r/jailbreak/   and search for their issues and let Luca and everyone else involve work peacefully.

Geez people seriously instead of helping every time u open an issue u r wasting their time to actually concentrate in this project bc ppl r so impatient and don't even take the time to read the projects read me file where it says incomplete they're working on adding more devices and sorting out actual issues with the code PLEASE PPL READ AND WAIT WHEN ITS READY IM PRETTY SURE THEY'LL POST IT ON TWITTER AND LUCA'S WEBSITE.
